name: Deploy to the production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 162.0.226.65
          username: cubancigarsinusa
          password: 9p9(3RUfLy_1
          script: |
            cd /home/cubancigarsinusa/repositories/cubancigarsinusa	
            git add .
            git commit -m "merge previous changes"
            git pull origin main
            npm install
            npm run export
