name: Deploy to the production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Verify key is added correctly
          cat ~/.ssh/id_rsa

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ~/.ssh/id_rsa  # Use private key here
          script: |
            cd /home/cubancigarsinusa/public_html/
            git add .
            git commit -m "merge previous changes"
            git pull origin main
            npm run setup
            npm run build
